name: Emscripten/Pyodide build

on:
  workflow_call:

jobs:
  build-wasm-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build WASM wheel
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_PLATFORM: pyodide
      - name: Upload package
        uses: actions/upload-artifact@v6
        with:
          name: wasm_wheel
          path: ./wheelhouse/*_wasm32.whl
          if-no-files-found: error
